- name: install nginx with condition
  hosts: localhost
  become: yes
  vars:
    demo: true
  tasks:
  - name: install nginx if demo=true
    dnf:
      name: nginx
      state: present
    when: demo == true 

