---
- name: Verify apache installation
  hosts: localhost
  vars:
    http_port: 80
    max_clients: 200
  become: yes
  tasks:
    - name: Ensure apache is at the latest version
      ansible.builtin.yum:
        name: postfix
        state: latest
      notify:
        - Restart apache


  handlers:
    - name: Restart apache
      ansible.builtin.debug:
        msg: "Installed successfully"