- name: install nginx with condition
  hosts: localhost
  become: yes
  tasks:
  - name: install nginx if demo=true
    dnf:
      name: "{{ item.name }}"
      state: "{{ item.statet }}"
    loop: 
    - { name: git , state: present}
    - { name: postfix , state: absent}
