- name: Install nginx and configure it
  hosts: shell
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present
        become: true

    - name: Start Nginx service
      service:
        name: nginx
        state: stopped
        become: true

      
