- name: Install nginx and configure it
  hosts: web
  become: yes
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present
      become: true
    - name: Start Nginx service
      service:
        name: nginx
        state: started
      become: true
      
