- name: demo for variables
  hosts: localhost
  vars_prompt:
  - name: Name
    prompt: "please enter username"
    private: no
  - name: Age
    prompt: "please enter age"
    private: no
    
     
  tasks:
  - name: printing message
    ansible.builtin.debug:
      msg="Hi {{Name}} ,Age :{{Age}}"